name: eventsuffle-dev
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://user:password@postgres/eventsuffle
    volumes:
      - ./src:/app/src
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventsuffle
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U user -d eventsuffle -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
