name: eventsuffle-prod
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventsuffle
