name: eventshuffle-prod
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://user:password@postgres/eventshuffle
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventshuffle
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U user -d eventshuffle -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
