name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verification:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.16
      - name: Setup dependencies
        run: bun install --frozen-lockfile
      - name: Check code formatting
        run: bun run format:check
      - name: Check linter
        run: bun run lint:check
      - name: Build application
        run: bun run build
      - name: Run tests
        run: bun run test
